FROM centos:7

COPY ./bootstrapcvmfswestlife.sh /bootstrapcvmfswestlife.sh
COPY ./bootstrapdocker.sh /bootstrapdocker.sh
COPY ./bootstrapsso.sh /bootstrapsso.sh
COPY ./install.sh /install.sh

RUN chmod +x /bootstrapcvmfswestlife.sh
RUN chmod +x /bootstrapdocker.sh
RUN chmod +x /bootstrapsso.sh
RUN chmod +x /install.sh
