# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

# Vagrant.require_version "< 1.9.4" # 1.9.4 bug in connecting VM 
$script = <<-SCRIPT
  yum install -y https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm
  yum install -y cvmfs cvmfs-config-default
  cvmfs_config setup
  echo "CVMFS_REPOSITORIES=west-life.egi.eu,wenmr.egi.eu
  #change it to local http proxy instance - squid, or similar
  CVMFS_HTTP_PROXY=DIRECT
  " >/etc/cvmfs/default.local
  service autofs restart
  cvmfs_config probe
  yum install -y httpd mod_ssl
  setenforce 0
  firewall-cmd --zone=public --add-port=80/tcp --permanent
  firewall-cmd --reload
  ln -s /cvmfs/west-life.egi.eu/tools/mono/latest/bin/mono /bin/mono
  /cvmfs/west-life.egi.eu/software/virtualfolder/latest/bootstrap/bootstrapcloud.sh
  systemctl daemon-reload
  service westlife-metadata restart
  echo I am provisioning...
  date > /etc/vagrant_provisioned_at
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.box = "westlife-eu/scientific_7"
  if Vagrant::VERSION =~ /^1.9.3/
    puts "vagrant version 1.9.3, fixing host_ip configuration "
    # forward standard web
    config.vm.network "forwarded_port", host_ip: "127.0.0.1", guest: 80, host: 8080
  else
    if Vagrant::VERSION =~ /^1.9.4/
      puts "vagrant version 1.9.4 detected. Upgrade to version 1.9.5+ or downgrade to version 1.9.3 or bellow"
      exit
    else
      puts "vagrant version:"
      puts Vagrant::VERSION
      # forward standard web
      config.vm.network "forwarded_port", guest: 80, host: 8080
    end
  end
  config.vm.provider "virtualbox" do |vb|
  # Display the VirtualBox GUI when booting the machine
    vb.gui = false
  #
  #   # Customize the amount of memory on the VM:
    vb.memory = "2048"
    vb.cpus = "2"
    vb.customize ["modifyvm", :id, "--vram", "16"]
  end
  config.vm.synced_folder ".", "/vagrant"
  config.vm.synced_folder "../../..", "/vagrant_data"

  # uncomment/comment desired bootstrap type, if VM should be build from sources use bootstrapsources.sh
  # otherwise(default) use bootstrapcvmfs.sh  

  config.vm.provision "shell",  
    inline: $script
end
